retain_result: checkpoints/Traditional_RFS_on_retain197_epoch10_phi/eval_results/ds_size400/eval_log_aggregated.json
#model_path: /data/urveim/talmahmud/IUL/checkpoints/OSL_4shards_P50_epoch_10_lr_5e-05_phi_mrr0.1_trr0.85_cali4/Final_Model
#ckpt_result: ${model_path}/eval_results/ds_size400/eval_log_aggregated.json
ckpt_result: checkpoints/APA_UM_forget03_phi/eval_results/ds_size400/eval_log_aggregated.json
method_name: APA_UM_forget03_phi
submitted_by: tamim
save_file: results/APA_UM_forget03_phi.csv