model_family: phi
#model_path: /data/urveim/talmahmud/IUL/checkpoints/OSL_4shards_P50_epoch_10_lr_5e-05_phi_mrr0.1_trr0.85_cali4/Final_Model
model_path: checkpoints/APA_UM_forget03_phi
save_dir: ${model_path}/eval_results/ds_size${ds_size}

#dataset path for each of the 4 datasets to be evaluated
data_path: [talmahmud/tofu_custom_split_UnReL, talmahmud/tofu_custom_split_UnReL, talmahmud/tofu_custom_split_UnReL, talmahmud/tofu_custom_split_UnReL]
split: forget03_perturbed
split_list:
  - retain_perturbed
  - real_authors_perturbed
  - world_facts_perturbed
  - ${split}

question_key: [question, question, question, question]
answer_key: [answer, answer, answer, answer]

base_answer_key: [paraphrased_answer, answer, answer, paraphrased_answer]
perturbed_answer_key: [perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer]

eval_task: [eval_log, eval_real_author_wo_options, eval_real_world_wo_options, eval_log_forget]

generation:
  max_length: 200
  max_new_tokens: null

save_generated_text: true

ds_size: 400

overwrite: true
use_pretrained: false

batch_size: 20
reinitialize_weights: false

retain_result: null

