model_family: phi

resume_from: /data/urveim/talmahmud/IUL/checkpoints/OSL_4shards_P50_epoch_10_lr_5e-05_phi_mrr0.1_trr0.85_cali4/shard4_3
#resume_from: /home/talmahmud/IUL/checkpoints/OSL_phi/shard8_7

data_paths:
  # - talmahmud/tofu_resplit
  # - talmahmud/tofu_resplit
  # - talmahmud/tofu_resplit
  # - talmahmud/tofu_resplit
  # - talmahmud/tofu_resplit
  # - talmahmud/tofu_resplit
  # - talmahmud/tofu_resplit
  - talmahmud/tofu_custom_split_UnReL

splits:
  # - shard8_1
  # - shard8_2
  # - shard8_3
  # - shard8_4
  # - retain_shard8_6_forget01DP
  # - shard8_6
  # - retain_shard4_3_forget10DP
  - retain_shard4_4_forget03

batch_size: 4
gradient_accumulation_steps: 4
num_epochs: 10
lr: 5e-5
weight_decay: 0.01
seed: 42

save_dir: /data/urveim/talmahmud/IUL/checkpoints/OSL_4shards_P50_epoch_10_lr_5e-05_phi_mrr0.1_trr0.85_cali4

continual:
  osl:
    mrr: 0.10
    trr: 0.85
    cali_batches: 4
    target_linear_only: true
